evader:
  mass: 500.0
  max_acceleration: 20.0
  top_speed: 300.0
  drag_coefficient: 0.02
  awareness_mode: 1
  turn_rate: 3.141592653589793
  up_vector: [0.0, 0.0, 1.0]
  stall_angle: 1.0471975511965976
pursuer:
  mass: 1000.0
  max_acceleration: 30.0
  top_speed: 350.0
  drag_coefficient: 0.03
  turn_rate: 4.71238898038469
  up_vector: [0.0, 0.0, 1.0]
  stall_angle: 1.3089969389957472
gravity: 9.81
time_step: 0.1
capture_radius: 1.0
shaping_weight: 0.05
target_position: [1000.0, 0.0, 0.0]
pursuer_start:
  cone_half_angle: 0.7853981633974483
  min_range: 1000.0
  max_range: 5000.0
  force_target_radius: 500.0
  initial_speed_range: [0.0, 50.0]
initial_positions:
  evader: [0.0, 0.0, 3000.0]
