evader:
  # Mass of the evader aircraft [kg]
  mass: 1500.0
  # Maximum acceleration magnitude the evader can command [m/s^2]
  max_acceleration: 20.0
  # Upper speed limit [m/s]
  top_speed: 300.0
  # Dimensionless coefficient modelling drag
  drag_coefficient: 0.02
  # How much information the evader gets about the pursuer
  #   1 - evader has no knowledge of the pursuer
  #   2 - only the distance to the pursuer is observed
  #   3 - evader receives the unit vector pointing to the pursuer
  #   4 - full pursuer position is known (values >4 behave the same)
  awareness_mode: 1
  # Maximum yaw rotation rate [deg/s]
  yaw_rate: 5
  # Maximum pitch rotation rate [deg/s]
  pitch_rate: 10
  # Initial force direction
  up_vector: [0.0, 0.0, 1.0]
  # Maximum allowable pitch angle [deg]
  stall_angle: 45.0
pursuer:
  # Mass of the pursuer [kg]
  mass: 100.0
  # Maximum acceleration magnitude [m/s^2]
  max_acceleration: 30.0
  # Upper speed limit [m/s]
  top_speed: 350.0
  # Dimensionless coefficient modelling drag
  drag_coefficient: 0.03
  # Maximum yaw rotation rate [deg/s]
  yaw_rate: 10.0
  # Maximum pitch rotation rate [deg/s]
  pitch_rate: 15.0
  # Initial force direction
  up_vector: [0.0, 0.0, 1.0]
  # Maximum allowable pitch angle [deg]
  stall_angle: 55.0
# Downward gravitational acceleration [m/s^2]
gravity: 9.81
# Simulation time step [s]
time_step: 0.1
# Duration of one episode [min]
episode_duration: 40
# Distance at which capture is considered successful [m]
capture_radius: 1.0
# Distance within which the evader receives reward when hitting the ground [m]
target_reward_distance: 100.0
# Weight for shaping rewards
shaping_weight: 0.05
# Coordinates of the evader's goal [m]
target_position: [0, 0.0, 0.0]
evader_start:
  # Range of initial horizontal distance from the goal [m]
  distance_range: [8000.0, 12000.0]
  # Starting altitude [m]
  altitude: 3000.0
pursuer_start:
  # Maximum half angle of the pursuer spawn cone [rad]
  cone_half_angle: 1.4
  # Minimum initial range from the evader [m]
  min_range: 1000.0
  # Maximum initial range from the evader [m]
  max_range: 5000.0
  # Radius around the evader target where the pursuer aims initially [m]
  force_target_radius: 500.0
  # Range of random initial speeds [m/s]
  initial_speed_range: [150.0, 250.0]
