# Q-learning training options
q_learning:
  episodes: 5000
  lr: 0.001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 0.995
  batch_size: 64
  buffer_size: 50000
  target_update: 200
  eval_freq: 50
  max_steps: 500
  log_dir: null
